/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FCGEe4soYTf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useEffect } from "react"

export default function QuizPages() {
  const [selectedAnswer, setSelectedAnswer] = useState(null)
  const [timeRemaining, setTimeRemaining] = useState(60)
  useEffect(() => {
    const timer = setInterval(() => {
      setTimeRemaining((prevTime) => prevTime - 1)
    }, 1000)
    return () => clearInterval(timer)
  }, [])
  const handleAnswerSelect = (answer: any) => {
    setSelectedAnswer(answer)
  }
  const isCorrect = (answer: any) => {
    return answer === "The correct answer"
  }
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="max-w-md w-full p-6 rounded-lg shadow-lg bg-card">
        <h1 className="text-2xl font-bold mb-4">Quiz Question</h1>
        <p className="text-muted-foreground mb-6">What is the correct answer to this question?</p>
        <div className="flex justify-between items-center mb-4">
          <p className="text-muted-foreground">Time Remaining: {timeRemaining}s</p>
          {timeRemaining === 0 && <p className="text-red-500 font-bold">Time is up!</p>}
        </div>
        <div className="space-y-2">
          <button
            onClick={() => handleAnswerSelect("Answer 1")}
            className={`w-full px-4 py-2 rounded-md transition-colors ${
              selectedAnswer === "Answer 1"
                ? isCorrect("Answer 1")
                  ? "bg-green-500 text-primary-foreground"
                  : "bg-red-500 text-primary-foreground"
                : "bg-card hover:bg-muted"
            }`}
          >
            Answer 1
          </button>
          <button
            onClick={() => handleAnswerSelect("Answer 2")}
            className={`w-full px-4 py-2 rounded-md transition-colors ${
              selectedAnswer === "Answer 2"
                ? isCorrect("Answer 2")
                  ? "bg-green-500 text-primary-foreground"
                  : "bg-red-500 text-primary-foreground"
                : "bg-card hover:bg-muted"
            }`}
          >
            Answer 2
          </button>
          <button
            onClick={() => handleAnswerSelect("The correct answer")}
            className={`w-full px-4 py-2 rounded-md transition-colors ${
              selectedAnswer === "The correct answer"
                ? "bg-green-500 text-primary-foreground"
                : "bg-card hover:bg-muted"
            }`}
          >
            The correct answer
          </button>
          <button
            onClick={() => handleAnswerSelect("Answer 4")}
            className={`w-full px-4 py-2 rounded-md transition-colors ${
              selectedAnswer === "Answer 4"
                ? isCorrect("Answer 4")
                  ? "bg-green-500 text-primary-foreground"
                  : "bg-red-500 text-primary-foreground"
                : "bg-card hover:bg-muted"
            }`}
          >
            Answer 4
          </button>
        </div>
      </div>
    </div>
  )
}
